spring.application.name=demo
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/assistente_corporativo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

gemini.api.key=${GEMINI_API_KEY}
