spring.application.name=demo
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/assistente_corporativo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.ai.google.genai.api-key=AQ.Ab8RN6KeHXPaZ86WVcPMtSB-TpCRWJbY58QnFxgStRO3wLuQKQ
